### ISSUE TITLE
Gallery mode

### ISSUE THREAD

**Issue by dimmuboy** [hunzaboy/Light-Modal#4]
hi there,
I need to replace my iziModal component and this is the best adept. There's missing me one thing - gallery mode that makes possible to switching between modals without close them.
Is possible to implement this feature please?

**Comment by hunzaboy** [comment]
yes, i am currently implementing it.  It will again be pure CSS based approach without the use of any js. Hope you will like it. I might publish it today or tomorrow.

**Comment by hunzaboy** [comment]
@dimmuboy  : Added new gallery mode :)

https://hunzaboy.github.io/Light-Modal/
