### ISSUE TITLE
Trigger via javascript

### ISSUE THREAD

**Issue by ua0leg** [hunzaboy/Light-Modal#8]
Is there any chance to show modal when page loads?
I've tried to create hidden `a` tag with `.trigger('click');` on `$( document ).ready()`  but it didn't work.

**Comment by hunzaboy** [comment]
Sorry for the late reply.

Does the a tag contan ? e.g yourl.com/#light-modal ?

**Comment by ua0leg** [comment]
Yep, the `<a href="#modal_id">` tag contans the link to modal without `?` sign

**Comment by hunzaboy** [comment]
https://stackoverflow.com/questions/25097181/trigger-click-event-on-a-href-element this might help
