### ISSUE TITLE
Scrolling to top behavior

### ISSUE THREAD

**Issue by alonsoct00** [hunzaboy/Light-Modal#9]
Hi! I have a scroll-to-top when I click the both close buttons, when the modal is closed, the browser window goes to the top.

How can prevent this behavior, I already tried to use the "fixed" attribute in the body, and the preventdefault with JS. 

Thanks

**Comment by alonsoct00** [comment]
I've been looking for solutions and adding a slash on the anchor solves it:
`<a href="#/" class="light-modal-close-icon" aria-label="close">&times;</a>`
I don't know if it's good practice

**Comment by alonsoct00** [comment]
I've been looking for solutions and adding a slash on the anchor solves it:
<a href="#/" class="light-modal-close-icon" aria-label="close">&times;</a>

I don't know if it's good practice

**Comment by alonsoct00** [comment]
I've been looking for solutions and adding a slash on the anchor solves it:
<a href="#/" class="light-modal-close-icon" aria-label="close">&times;</a>

I don't know if it's good practice

**Comment by alonsoct00** [comment]
I've been looking for solutions and adding a slash on the anchor solves it:
<a href="#/" class="light-modal-close-icon" aria-label="close">&times;</a>

I don't know if it's good practice

**Comment by hunzaboy** [comment]
That works fine for this CSS modal. I also added it to the demo page :)

**Comment by TPF1** [comment]
Thanks for the solution, I am triggering the modal inside my jquery instead of doing a button/href.

`$(".box").click(function(e) {
window.location="#my-modal"; 
}`

The solution above is not working in this case. Am I doing something wrong ?
